### ISSUE TITLE
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by iamyoki** [FRSOURCE/cypress-plugin-visual-regression-diff#113]
**Describe the bug**
Here is my test:
```js
it.only('test', () => {
    cy.matchImage();
  });
```

First run is okay, but not after then.
I think it's related to my chinese character filename.

Here is the error message:
```
Error:       InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/support/e2e.js:256:76)
From previous event:
    at Context.thenFn (http://localhost:3000/__cypress/runner/cypress_runner.js:138969:63)
    at Context.then (http://localhost:3000/__cypress/runner/cypress_runner.js:139391:21)
    at wrapped (http://localhost:3000/__cypress/runner/cypress_runner.js:157145:19)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:155901:15
From previous event:
    at CommandQueue.runCommand (http://localhost:3000/__cypress/runner/cypress_runner.js:155879:17)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:156032:19)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:156061:16
```
![image](https://user-images.githubusercontent.com/74389358/189266950-3cb46c02-972f-4aa8-9863-5d25c45b9333.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS and version: [e.g. Windows 10 build. 19043.1319]
 - Browser and version [e.g. chrome 22]
 - Cypress version [e.g. 8.6.0]

**Additional context**

**Comment by FRSgit** [comment]
Hi @iamyoki!
Thank you for the issue and PR 🙇

It seems that you've noticed the issue correctly - seems like non-latin characters need to be escaped since the filename is serialized into on anchor link. Let's try to get this PR merged quickly! 💪
