### ISSUE TITLE
Invalid PNG error

### ISSUE THREAD

**Issue by dhulme** [FRSOURCE/cypress-plugin-visual-regression-diff#173]
**Describe the bug**
When capturing screenshots I intermittently get an "Invalid PNG" error in the console. 

```
TypeError: Invalid PNG
      at Object.addMetadata (C:\dev\cg-react-components\node_modules\meta-png\dist\meta-png.umd.js:1:886)
      at addPNGMetadata (C:\dev\cg-react-components\node_modules\@frsource\cypress-plugin-visual-regression-diff\src\image.utils.ts:12:3)
      at writePNG (C:\dev\cg-react-components\node_modules\@frsource\cypress-plugin-visual-regression-diff\src\image.utils.ts:23:5)
      at compareImagesTask (C:\dev\cg-react-components\node_modules\@frsource\cypress-plugin-visual-regression-diff\src\task.hook.ts:157:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**

The issue is intermittent. A test might pass one time and fail another. All my tests are component tests. The subject of the screenshot does not seem to matter. 

**Expected behavior**

Screenshots capture without error

**Screenshots**

![image](https://user-images.githubusercontent.com/1234671/199941006-4b124bc9-396a-49a2-b827-00a4458dc0ff.png)

**Please complete the following information:**

- Package version: 3.1.1
- OS and version: Windows 10
- Browser and version Chrome/Firefox
- Cypress version 10.11.0

**Additional context**

I think the problem is due to the recently added cleanup functionality using the metadata. I have logged out the PNG buffer and there is data there.

**Comment by FRSgit** [comment]
Hey @dhulme,

Thank for the bug report! I've just tried to reproduce this error on the example project from this repo, but not luck 😞
Can you try to fork this repo and set up a reproduction example please?🙏

**Comment by xibman** [comment]
+1 for this bug. 

More complete stack trace 

`  at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:145912:78)
      at tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:11318:23)
      at Promise._settlePromiseFromHandler (http://localhost:5173/__cypress/runner/cypress_runner.js:9253:31)
      at Promise._settlePromise (http://localhost:5173/__cypress/runner/cypress_runner.js:9310:18)
      at Promise._settlePromise0 (http://localhost:5173/__cypress/runner/cypress_runner.js:9355:10)
      at Promise._settlePromises (http://localhost:5173/__cypress/runner/cypress_runner.js:9431:18)
      at _drainQueueStep (http://localhost:5173/__cypress/runner/cypress_runner.js:6025:12)
      at _drainQueue (http://localhost:5173/__cypress/runner/cypress_runner.js:6018:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:5173/__cypress/runner/cypress_runner.js:6034:5)
      at Async.drainQueues (http://localhost:5173/__cypress/runner/cypress_runner.js:5904:14)
  From Your Spec Code:
      at Context.<anonymous> (http://localhost:5173/__cypress/src/node_modules/.vite/deps/@frsource_cypress-plugin-visual-regression-diff.js?v=83b79b34:173:27)
      at getRet (http://localhost:5173/__cypress/runner/cypress_runner.js:139204:20)
      at tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:11318:23)
      at Promise.attempt.Promise.try (http://localhost:5173/__cypress/runner/cypress_runner.js:8592:29)
      at Context.thenFn (http://localhost:5173/__cypress/runner/cypress_runner.js:139218:63)
      at Context.then (http://localhost:5173/__cypress/runner/cypress_runner.js:139640:21)
      at wrapped (http://localhost:5173/__cypress/runner/cypress_runner.js:157508:19)
      at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:156244:15)
  
  From Node.js Internals:
    TypeError: Invalid PNG
        at Object.getMetadata (/Users/xibman/Koala/Projects/monorepo/node_modules/meta-png/dist/meta-png.umd.js:1:1565)
        at getPNGMetadata (/Users/xibman/Koala/Projects/monorepo/node_modules/@frsource/cypress-plugin-visual-regression-diff/src/image.utils.ts:14:3)
        at isImageCurrentVersion (/Users/xibman/Koala/Projects/monorepo/node_modules/@frsource/cypress-plugin-visual-regression-diff/src/image.utils.ts:16:3)
        at compareImagesTask (/Users/xibman/Koala/Projects/monorepo/node_modules/@frsource/cypress-plugin-visual-regression-diff/src/task.hook.ts:143:25)
    at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by menelikw** [comment]
yeah i have the same issue. Any update or workaround please?

**Comment by menelikw** [comment]
no cigar on either of those solutions. But thanks for responding so quickly, removing that isPNG check alltogether solved the problem for me but obviously isn't a solution

**Comment by FRSgit** [comment]
Hm, so the issue must be the PNG, because the second code is a `isPNG` check from [here](https://github.com/sindresorhus/is-png/blob/main/index.js#L6-L13) (1 milion downloads per week library, so I believe this code is tested 😄). Can you send me a PNG file that fails for any of you? In a case of @xibman it's an old screenshot we're comparing against (so, the file without `.actual` or `.diff` suffix)

**Comment by menelikw** [comment]
File names are:

alert-component-when-the-status-is-set-to-error-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0.actual.png
alert-component-when-the-status-is-set-to-error-should-render-error-icon-chrome #0.actual.png
alert-component-when-the-status-is-set-to-info-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0.png
alert-component-when-the-status-is-set-to-info-should-render-info-icon-chrome #0.png
alert-component-when-the-status-is-set-to-promotional-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0.png
alert-component-when-the-status-is-set-to-promotional-should-render-promotional-icon-chrome #0.png
alert-component-when-the-status-is-set-to-success-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0.png
alert-component-when-the-status-is-set-to-success-should-render-success-icon-chrome #0.png
alert-component-when-the-status-is-set-to-system-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0.actual.png
alert-component-when-the-status-is-set-to-system-should-render-system-icon-chrome #0.actual.png
alert-component-when-the-status-is-set-to-warning-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0.png
alert-component-when-the-status-is-set-to-warning-should-render-warning-icon-chrome #0.png

The actual images:
![alert-component-when-the-status-is-set-to-error-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0 actual](https://user-images.githubusercontent.com/5381226/200824282-573e7bef-9990-4898-9e1a-8005717ec289.png)
![alert-component-when-the-status-is-set-to-error-should-render-error-icon-chrome #0 actual](https://user-images.githubusercontent.com/5381226/200824287-470b21d0-469d-451c-8363-2a6756383e4d.png)
![alert-component-when-the-status-is-set-to-info-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824292-92367995-a932-41b3-a8d5-7719650b8bb5.png)
![alert-component-when-the-status-is-set-to-info-should-render-info-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824293-eae1161b-1f8a-4909-b6f0-87baedc2ba8d.png)
![alert-component-when-the-status-is-set-to-promotional-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824294-f2942df7-095f-4395-ba3e-6a50dde9b90b.png)
![alert-component-when-the-status-is-set-to-promotional-should-render-promotional-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824295-e6702e91-960b-4a55-8af0-23a020e3d656.png)
![alert-component-when-the-status-is-set-to-success-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824296-3400f6bf-1e37-4fe2-9c10-ed9018c38a3d.png)
![alert-component-when-the-status-is-set-to-success-should-render-success-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824300-7c2ec0d8-3eec-4a30-9c7f-c7327d9e5d93.png)
![alert-component-when-the-status-is-set-to-system-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0 actual](https://user-images.githubusercontent.com/5381226/200824301-df6e7c98-4cab-4e73-977b-7ccd81a2a04a.png)
![alert-component-when-the-status-is-set-to-system-should-render-system-icon-chrome #0 actual](https://user-images.githubusercontent.com/5381226/200824305-10d9adc0-89ec-4911-9ab7-003f334a2ce3.png)
![alert-component-when-the-status-is-set-to-warning-and-a-custom-icon-was-set-should-render-custom-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824306-693c829e-9f3d-496f-8500-7eb28f825c95.png)
![alert-component-when-the-status-is-set-to-warning-should-render-warning-icon-chrome #0](https://user-images.githubusercontent.com/5381226/200824307-c671ccbf-88ca-4974-9994-29250840e25c.png)

**Comment by menelikw** [comment]
If however I capture the whole component like this: 
![alert-component-when-linktext-and-linktarget-are-set-renders-with-a-custom-link-chrome #0](https://user-images.githubusercontent.com/5381226/200824443-6b994922-47fe-41a2-96d2-c68c36b94878.png)

they all work fine

**Comment by menelikw** [comment]
[snapshot-images.zip](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/files/9975263/snapshot-images.zip)

**Comment by adamdehaven** [comment]
FYI I get this same error when adding the plugin to a repository for the first time. On my machine, it runs fine; however, I get the "Invalid PNG" error when running in GitHub actions.

**Comment by xibman** [comment]
@FRSgit 

I try several case to be sure the problem come from the version 3 and more.

I remove all the screenshot manually and then launch the full process. It work on first launch with `updateImages:true`
Then all test are launch with `updateImages:false`. It fail not all time and not on the same test.

Dev env:
os: macos monterey 12.6.1 (21G217)
node v16.17.0
cypress 10.11.0 or 11.0.0 (only component testing for vue components)
bundler: vite 3.1.x or 3.2.x

**Comment by menelikw** [comment]
Sorry I can't share the repo, it's behind many walls of auth lol. I'll create a replica

**Comment by dhulme** [comment]
Hi @FRSgit, I've been doing some research, Replacing the isPng check with the one you linked to fixes things for me. I also created a simple node script to test  an example image and it shows the current check fails, but the new check passes. (see attached zip). If I produce a test png in MS paint though, it passes both checks. So there must be something bu
[test.zip](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/files/9980316/test.zip)
ggy with the current checking method!

**Comment by FRSgit** [comment]
Thank you all for the messages, we're really having quite intense issue-fixing process going on here 😄 ❤️ 

@dhulme [I've created a PR with this fix on `meta-png` library repo](https://github.com/lucach/meta-png/pull/4). Last time its author was really quick and released new version the same day [I've created a PR](https://github.com/lucach/meta-png/pull/3). So, hopefully `meta-png` will get release with a fix and I'll be able ship it to you this week.

If that won't help for @menelikw and @xibman I'll do one more round of trying to reproduce it (@menelikw then your repo would be super useful 🙏 ).

I'll keep you updated

**Comment by menelikw** [comment]
Yeah I'll do that this evening uk time.

**Comment by menelikw** [comment]
Thanks for being so responsive man. I'll try to do some more debugging too

**Comment by FRSgit** [comment]
Hey @dhulme, I'm happy to announce that issue was tackled by the author of `meta-png` and should be fixed now.
I've just released new version of `@frsource/cypress-plugin-visual-regression-diff` (v3.1.4), please check it out and let me know if that fixes all of these problems for you!

**Comment by FRSgit** [comment]
Friendly bump 🙂

**Comment by dhulme** [comment]
Hi, I can confirm this has resolved the issue! Thank you :)

**Comment by xibman** [comment]
@FRSgit  Thanks a lot i've just done the update, it work well !

**Comment by menelikw** [comment]
hello i'm back. sorry was balls deep in code. thanks for the fix @FRSgit awesome work. For me it works on first run but fails thereafter... 

From Node.js Internals:
  Error: unrecognised content at end of stream
      at module.exports.SyncReader.process (/Users/menelikwilliams/projects/story-book-preact/node_modules/pngjs/lib/sync-reader.js:43:11)
      at module.exports (/Users/menelikwilliams/projects/story-book-preact/node_modules/pngjs/lib/parser-sync.js:68:10)
      at Object.read (/Users/menelikwilliams/projects/story-book-preact/node_modules/pngjs/lib/png-sync.js:7:10)
      at compareImagesTask (/Users/menelikwilliams/projects/story-book-preact/node_modules/@frsource/cypress-plugin-visual-regression-diff/src/task.hook.ts:85:32)

you wan't me to raise a new issue?

**Comment by FRSgit** [comment]
@menelikw Hey,

Yes, it's a separate issue - something not related to this ticket.

But I see it was reported today already: https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/issues/184
Please follow that report for updates
